all: # keys must be unique, i.e. only one 'hosts' per group
    vars:
        ansible_user: jenkins
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        global_var2: common
        artifacts_dir: artifacts
        components:
            app:
                component_artifact_url: https://raw.githubusercontent.com/thfai2000/sample-app/release/{{ component_version }}/app.html.j2
                component_install_script: |
                    sudo mkdir -p /www
                    sudo mv artifacts/app/app.html /www/.
                component_start_script: "sudo service nginx restart"
                component_stop_script: "sudo service nginx stop"
                component_service_account: 'jenkins'
            web:
                component_artifact_url: https://raw.githubusercontent.com/thfai2000/sample-app/release/{{ component_version }}/app.conf.j2
                component_install_script: |
                    sudo mv artifacts/web/app.conf /etc/nginx/conf.d/.
                component_start_script: "sudo service nginx restart"
                component_stop_script: "sudo service nginx stop"
                component_service_account: 'jenkins'
                nginx_listen_port: 8081